[package]
name = "verge-platform-linux-x11"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
verge-core = { path = "../../../core" }

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = { version = "0.14", features = ["randr", "shape"] }
fontdue = "0.9"
